version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - errname
    - errorlint
    - gosec
    - prealloc
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gosec:
    excludes:
      - G104

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/yurii-merker/commute-tracker

issues:
  exclude-dirs:
    - internal/db
