// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Route struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	Label          string      `json:"label"`
	FromStationCrs string      `json:"from_station_crs"`
	ToStationCrs   string      `json:"to_station_crs"`
	DepartureTime  pgtype.Time `json:"departure_time"`
	DaysOfWeek     int32       `json:"days_of_week"`
	IsActive       bool        `json:"is_active"`
	AlertOffsets   []int32     `json:"alert_offsets"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	TelegramChatID int64              `json:"telegram_chat_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	State          string             `json:"state"`
	SystemAlerts   bool               `json:"system_alerts"`
}
