// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoutesByUserID = `-- name: CountRoutesByUserID :one
SELECT count(*) FROM routes
WHERE user_id = $1
`

func (q *Queries) CountRoutesByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (user_id, label, from_station_crs, to_station_crs, departure_time, days_of_week, alert_offsets)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, label, from_station_crs, to_station_crs, departure_time, days_of_week, is_active, alert_offsets
`

type CreateRouteParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Label          string      `json:"label"`
	FromStationCrs string      `json:"from_station_crs"`
	ToStationCrs   string      `json:"to_station_crs"`
	DepartureTime  pgtype.Time `json:"departure_time"`
	DaysOfWeek     int32       `json:"days_of_week"`
	AlertOffsets   []int32     `json:"alert_offsets"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.UserID,
		arg.Label,
		arg.FromStationCrs,
		arg.ToStationCrs,
		arg.DepartureTime,
		arg.DaysOfWeek,
		arg.AlertOffsets,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FromStationCrs,
		&i.ToStationCrs,
		&i.DepartureTime,
		&i.DaysOfWeek,
		&i.IsActive,
		&i.AlertOffsets,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const getActiveRoutesForWeekday = `-- name: GetActiveRoutesForWeekday :many
SELECT id, user_id, label, from_station_crs, to_station_crs, departure_time, days_of_week, is_active, alert_offsets FROM routes
WHERE is_active = true
  AND (days_of_week & $1::int) != 0
`

func (q *Queries) GetActiveRoutesForWeekday(ctx context.Context, dollar_1 int32) ([]Route, error) {
	rows, err := q.db.Query(ctx, getActiveRoutesForWeekday, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.FromStationCrs,
			&i.ToStationCrs,
			&i.DepartureTime,
			&i.DaysOfWeek,
			&i.IsActive,
			&i.AlertOffsets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveRoutesWithChatID = `-- name: GetActiveRoutesWithChatID :many
SELECT r.id, r.user_id, r.label, r.from_station_crs, r.to_station_crs, r.departure_time, r.days_of_week, r.is_active, r.alert_offsets, u.telegram_chat_id
FROM routes r
JOIN users u ON u.id = r.user_id
WHERE r.is_active = true
  AND (r.days_of_week & $1::int) != 0
`

type GetActiveRoutesWithChatIDRow struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	Label          string      `json:"label"`
	FromStationCrs string      `json:"from_station_crs"`
	ToStationCrs   string      `json:"to_station_crs"`
	DepartureTime  pgtype.Time `json:"departure_time"`
	DaysOfWeek     int32       `json:"days_of_week"`
	IsActive       bool        `json:"is_active"`
	AlertOffsets   []int32     `json:"alert_offsets"`
	TelegramChatID int64       `json:"telegram_chat_id"`
}

func (q *Queries) GetActiveRoutesWithChatID(ctx context.Context, dollar_1 int32) ([]GetActiveRoutesWithChatIDRow, error) {
	rows, err := q.db.Query(ctx, getActiveRoutesWithChatID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveRoutesWithChatIDRow{}
	for rows.Next() {
		var i GetActiveRoutesWithChatIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.FromStationCrs,
			&i.ToStationCrs,
			&i.DepartureTime,
			&i.DaysOfWeek,
			&i.IsActive,
			&i.AlertOffsets,
			&i.TelegramChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, user_id, label, from_station_crs, to_station_crs, departure_time, days_of_week, is_active, alert_offsets FROM routes
WHERE id = $1
`

func (q *Queries) GetRouteByID(ctx context.Context, id pgtype.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FromStationCrs,
		&i.ToStationCrs,
		&i.DepartureTime,
		&i.DaysOfWeek,
		&i.IsActive,
		&i.AlertOffsets,
	)
	return i, err
}

const getRoutesByUserID = `-- name: GetRoutesByUserID :many
SELECT id, user_id, label, from_station_crs, to_station_crs, departure_time, days_of_week, is_active, alert_offsets FROM routes
WHERE user_id = $1
ORDER BY departure_time
`

func (q *Queries) GetRoutesByUserID(ctx context.Context, userID pgtype.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, getRoutesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.FromStationCrs,
			&i.ToStationCrs,
			&i.DepartureTime,
			&i.DaysOfWeek,
			&i.IsActive,
			&i.AlertOffsets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRouteActive = `-- name: UpdateRouteActive :exec
UPDATE routes SET is_active = $2
WHERE id = $1
`

type UpdateRouteActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateRouteActive(ctx context.Context, arg UpdateRouteActiveParams) error {
	_, err := q.db.Exec(ctx, updateRouteActive, arg.ID, arg.IsActive)
	return err
}

const updateRouteDepartureTime = `-- name: UpdateRouteDepartureTime :exec
UPDATE routes SET departure_time = $2
WHERE id = $1
`

type UpdateRouteDepartureTimeParams struct {
	ID            pgtype.UUID `json:"id"`
	DepartureTime pgtype.Time `json:"departure_time"`
}

func (q *Queries) UpdateRouteDepartureTime(ctx context.Context, arg UpdateRouteDepartureTimeParams) error {
	_, err := q.db.Exec(ctx, updateRouteDepartureTime, arg.ID, arg.DepartureTime)
	return err
}
