// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_chat_id, state)
VALUES ($1, $2)
ON CONFLICT (telegram_chat_id) DO NOTHING
RETURNING id, telegram_chat_id, created_at, state, system_alerts
`

type CreateUserParams struct {
	TelegramChatID int64  `json:"telegram_chat_id"`
	State          string `json:"state"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.TelegramChatID, arg.State)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.State,
		&i.SystemAlerts,
	)
	return i, err
}

const getActiveChatIDsForWeekday = `-- name: GetActiveChatIDsForWeekday :many
SELECT DISTINCT u.telegram_chat_id
FROM users u
JOIN routes r ON r.user_id = u.id
WHERE r.is_active = true
  AND (r.days_of_week & (1 << $1::int)) != 0
`

func (q *Queries) GetActiveChatIDsForWeekday(ctx context.Context, dollar_1 int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, getActiveChatIDsForWeekday, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var telegram_chat_id int64
		if err := rows.Scan(&telegram_chat_id); err != nil {
			return nil, err
		}
		items = append(items, telegram_chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemAlertsChatIDs = `-- name: GetSystemAlertsChatIDs :many
SELECT DISTINCT u.telegram_chat_id
FROM users u
WHERE u.system_alerts = true
`

func (q *Queries) GetSystemAlertsChatIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getSystemAlertsChatIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var telegram_chat_id int64
		if err := rows.Scan(&telegram_chat_id); err != nil {
			return nil, err
		}
		items = append(items, telegram_chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByChatID = `-- name: GetUserByChatID :one
SELECT id, telegram_chat_id, created_at, state, system_alerts FROM users
WHERE telegram_chat_id = $1
`

func (q *Queries) GetUserByChatID(ctx context.Context, telegramChatID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByChatID, telegramChatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.State,
		&i.SystemAlerts,
	)
	return i, err
}

const toggleSystemAlerts = `-- name: ToggleSystemAlerts :one
UPDATE users SET system_alerts = NOT system_alerts
WHERE telegram_chat_id = $1
RETURNING system_alerts
`

func (q *Queries) ToggleSystemAlerts(ctx context.Context, telegramChatID int64) (bool, error) {
	row := q.db.QueryRow(ctx, toggleSystemAlerts, telegramChatID)
	var system_alerts bool
	err := row.Scan(&system_alerts)
	return system_alerts, err
}

const updateUserState = `-- name: UpdateUserState :exec
UPDATE users SET state = $2
WHERE telegram_chat_id = $1
`

type UpdateUserStateParams struct {
	TelegramChatID int64  `json:"telegram_chat_id"`
	State          string `json:"state"`
}

func (q *Queries) UpdateUserState(ctx context.Context, arg UpdateUserStateParams) error {
	_, err := q.db.Exec(ctx, updateUserState, arg.TelegramChatID, arg.State)
	return err
}
